dataset_type: 'pri30k_dataset'
df_path: './datasets/PRI30k/splits/pretrain_length_750_clean.csv'
batch_size: 4
data_root: './datasets/PRI30k/PDBs'
num_workers: 0
col_prot_name: PDB
col_prot_chain: Protein chains
col_na_chain: RNA chains
col_binding_site: Binding site renumbered merged
col_ligand: Binding ligands
pin_memory: True
cache_dir: './cache/pri30k'
loss_type: regression
strategy: separate

transform:
  - type: select_atom
    resolution: backbone
  - type: selected_region_with_distmap
    patch_size: 128
  - type: subtract_center_of_mass