epochs: 10 # 在预训练保留权重的轮数基础上微调20轮，当前预训练保留的是第48轮
patience: 150
output_dir: './outputs/finetune_from_pretrained/PRA201'
gpus:
  - 0
  
ckpt: null

run_name: 'SSDN_finetune_from_pretrain'
wandb: False
num_folds: 5