iters: 10500
epochs: 110
patience: 50
output_dir: './outputs/esm2rinalmo_650M/mCSM/blind_test'
gpus:
  - 0
ckpts: 
  - '/root/autodl-tmp/CoPRA/outputs/PRORNA_SSDN_pretrain_enhanced/log_fold_0/checkpoint/epoch=49-val_loss=1.241.ckpt'

run_name: 'esm2rinalmo_mmCSM_patch256'
wandb: False
num_folds: 1