epochs: 42 # 在预训练保留权重的轮数基础上微调20轮，当前预训练保留的是第48轮
patience: 150
output_dir: './outputs/wo_SSDNEnhanced_finetune/PRA201'
gpus: 1
  
ckpt: /root/autodl-tmp/CoPRA/outputs/wo_SSDN_Enhanced/log_fold_0/checkpoint/epoch=48-val_loss=2.455.ckpt

run_name: 'SSDN_finetune_from_pretrain'
wandb: False
num_folds: 5